### ISSUE TITLE
Error while referencing dot in template

### ISSUE THREAD

**Issue by ryan-bell-gea** [jason-dour/hugo-preproc#6]
Used `{{ . }}` in a template and received the following output: 

``` 
{commit abcdefg12345
Author: Ryan Bell <asdf@asdf.com>
Date:   Wed Feb 09 10:28:56 2022 -0500

    Corrected link to Business Portal

  .hugo/themes/geekdoc/data/menu/more.yaml | 2 +-
 .hugo/themes/geekdoc/layouts/shortcodes/hashes.html | 6 ++++--
}
```
I was unable to use dot to determine the object keys.

**Comment by jason-dour** [comment]
Thanks for the bug report!  I'll take a look at this.

**Comment by jason-dour** [comment]
Addressed with a combination of documentation and an additional template function.
